### PR TITLE
Allow any Sequence in `filter(where:in:)` and `filter(where:contains:)`

### PR DESCRIPTION
**Pull request by jegnux**
👋 Hello

It's me again 🙂 
Here's a minor change to allow any kind of Sequence in 2 methods instead of allowing only a `Set<T>`.

### CODE REVIEW

**Comment by vincent-pradeilles** [comment]
I like the idea, I'm just wondering one thing: what's going to happen if the sequence was to be infinite?

I ran this code in a Playground, and I saw that the contains function never returns:

```swift
import Foundation

let naturalIntegers = sequence(first: 0, next: { $0 + 1 })

naturalIntegers.contains(-1)
```

Maybe taking an `Array` instead of a `Sequence` could be a safer compromise?

**Comment by jegnux** [comment]
@vincent-pradeilles I'm not sure it's KeyPathKit responsibility to handle this issue.

Swift stdlib implement `contains` on `Sequence where Element : Equatable` and I'm just applying this to KeyPathKit.

→ http://bit.ly/2BEMewO
```swift
extension Sequence where Element : Equatable {
  /// Returns a Boolean value indicating whether the sequence contains the
  /// given element.
  ///
  /// This example checks to see whether a favorite actor is in an array
  /// storing a movie's cast.
  ///
  ///     let cast = ["Vivien", "Marlon", "Kim", "Karl"]
  ///     print(cast.contains("Marlon"))
  ///     // Prints "true"
  ///     print(cast.contains("James"))
  ///     // Prints "false"
  ///
  /// - Parameter element: The element to find in the sequence.
  /// - Returns: `true` if the element was found in the sequence; otherwise,
  ///   `false`.
  ///
  /// - Complexity: O(*n*), where *n* is the length of the sequence.
  @inlinable
  public func contains(_ element: Element) -> Bool {
    if let result = _customContainsEquatableElement(element) {
      return result
    } else {
      return self.contains { $0 == element }
    }
  }
}
```

**Comment by vincent-pradeilles** [comment]
Yeah that makes sense. I find it a bit weird that the Standard Library implements a function that potentially never returns (but I guess there are good reason for it?), but since they do, there is no point in restricting its use in a third-party framework.

If people want to run with scissors, I'm happy to oblige 😄

**Comment by jegnux** [comment]
Well, `sequence(first: 0, next: { $0 + 1 })` is an infinite sequence, so all methods (`forEach`, `map`, `flatMap`, etc...) will never end. It's the developper responsibility to use them wisely 🤷‍♂️

**Pull request merged**
